---
title: Amisoft Consulting
author: Darwin Groskleg
email: darwin@amisoft.ca
description: |2-
    Software, Strategty & Data
    [_part of the Obsideon_](https://www.obsideon.ca)
baseurl: ''
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
